nhsuk/connecting-to-services

app.js, app.json, package.json
=> :construction_worker: Set build pack for Heroku. Add package.json

app.js, package.json
Just checked deployment and app is running OK
=> :bug: Missing config settings

app/lib/openingTimesParser.js, app/lib/pharmacyMapper.js, app/middleware/services.js, app/views/results-open.nunjucks, app/views/results.nunjucks, test/integration/app.js, test/resources/syndication_responses/paged_pharmacies_postcode_search.xml, test/resources/syndication_responses/pharmacy_no_opening_times.xml, test/unit/lib/openingTimesParser.js
This work is complete but there is an issue with test execution times (#39)
=> Handle missing opening times for a pharmacy

app/lib/constants.js, app/middleware/locationValidator.js, app/middleware/services.js, app/middleware/urlUtils.js, test/unit/lib/openingTimesParser.js, test/unit/middleware/urlUtils.js
=> :ring: Use res.locals rather than req

public/css/nhsuk-ie6.css, public/css/nhsuk-ie7.css, public/css/nhsuk-ie8.css, public/css/nhsuk.css
=> :page_with_curl: Fix path to font CDN

app/views/results.nunjucks
=> :eggplant: Make address look more familiar

app/views/search.nunjucks
Spoke with Michael and he's OK with this change.
=> :oncoming_automobile: Set autofocus for usability

app/lib/getPharmacies.js
Rather than using `filter` (that can not be short-circuited/broken out of) I've switched to use a `for()` so that as soon as the condition of having (in this case) 10 'normal' results and 3 'open' results the loop is terminated.
Speed has increased (for this operation, in the example I am using) by ~50x. From ~300-400ms to <10ms!
=> :flashlight: Speed up open filter - break from loop asap

app/views/results.nunjucks, public/css/nhsuk.css
=> :sparkles: Tabbed navigation and results semantic markup changes

app/lib/postcodes.js, app/middleware/coordinateResolver.js, app/views/error-404.nunjucks, app/views/error.nunjucks, config/express.js, test/integration/app.js, test/unit/lib/postcodes.js
Also added code tests for postcode to location lookup fails
Fixes #126
Fixes #125
=> :pager: Add styled 404 page

app/lib/getPharmacies.js, app/lib/utils.js, app/middleware/prerender.js, test/unit/lib/utils.js
=> :black_large_square: Ensure openServices are not refs to nearbyServices

app/views/error-404.nunjucks, app/views/error.nunjucks, test/integration/app.js
Also changed page title to ensure context is given to screen readers
=> :sound: Ensure error messages are consistent

config/express.js, test/integration/app.js
Same deal as #180 but this time to allow eval so the survey are able to run. Pretty nasty downgrade in security...
=> :bug: Allow unsafe-eval for hotjar surveys

app/lib/getOpeningTimesMessage.js, app/lib/getPharmacies.js, package.json, test/unit/lib/getOpeningTimesMessage.js, test/unit/lib/getPharmacies.js
PR https://github.com/nhsuk/moment-opening-times/pull/39 will need merging and packaging before this is merged.
The moment-opening-times dependency in packages.json will then also need updating.
**Timings in connecting-to-services with the optimised OpeningTimes code:**
experimental/exceptional-opening-times
Nearby
happy path
✓ should return an object with nearby and open services (132ms)
master
Nearby
happy path
✓ should return an object with nearby and open services (101ms)
=> :bullettrain_front: Use optimised OpeningTimes

app/lib/getPharmacies.js, test/unit/lib/getPharmacies.js
Go back to a simpler (and quicker) time
=> :cancer: Revert segment search changes

app/middleware/logger.js, config/express.js, config/routes.js
Log requests to 'pages' as INFO
Log requests to all assets, including static assets, pages, etc as DEBUG
=> :white_flower: Change level of logging

app/middleware/getPharmacies.js, test/globalHooks.js, test/integration/resultsPage.js
=> :bug: Handle an unavailable API

package.json
See https://github.com/gtramontina/ghooks/issues/166 for more info
=> :wolf: Use Husky rather than deprecated ghooks

scripts/docker-style-name.sh, scripts/docker_ci.sh
Also replaces special characters in branch name, so docker can tag and push the branch.
=> Don't build Docker images for commits

.travis.yml, scripts/rancher_pr_deploy.sh, scripts/rancher_single_service_upgrade.py, scripts/rancher_staging_deploy.sh
- One for the deployment of PRs, creating a domain prefix for the services
- One to deploy staging, always using the master branch
- One to upgrade an individual "Service" in a stack
=> Add rancher deployment scripts

app/views/layout.nunjucks
In order to get the changes to no results styling working re #262
=> :bell: Bump version for cache bust

README.md
Also removed unused `PHARMACY_LIST_PATH`
=> :mag: Make numeric LOG_LEVEL explicit. Fix typos

rancher-config/docker-compose.yml
See: http://rancher.com/docs/rancher/v1.5/en/cli/variable-interpolation/#escaping-double-brackets
=> Fix Splunk tagging

CHANGELOG.md, app/lib/constants.js, app/middleware/locationValidator.js, app/middleware/setLocals.js, app/views/includes/no-english-location-no-results.nunjucks, app/views/includes/no-pharmacy-results.nunjucks, app/views/includes/no-results.nunjucks, test/integration/resultsPagePlace.js, test/integration/resultsPagePostcode.js, test/integration/resultsPageYourLocation.js
Improve readability of page content.
=> :book: Update content

app/lib/pageTitles.js, test/integration/resultsPagePlace.js, test/integration/resultsPagePostcode.js, test/unit/lib/pageTitles.js
=> :book: remove 'Find a pharmacy' prefix from results page title

app/lib/choicesServices.js, app/middleware/prerender.js, app/views/includes/openingTimes.nunjucks, app/views/includes/result-item.nunjucks, test/integration/resultsPageGeneral.js, test/integration/resultsPagePlace.js, test/resources/service-api-responses/-1,54.json, test/unit/lib/choicesServices.js
I'll refactor the choicesUrls into a single module at some point.
=> Review tweaks

CHANGELOG.md, README.md, app/middleware/locals.js, app/views/find-help.nunjucks, app/views/includes/google-search.nunjucks, config/config.js, doc/adr/0011-add-google-sitelinks-searchbox-metadata.md, docker-compose.yml, package.json, rancher-config/docker-compose.yml
=> :mag: add google search metadata

.snyk, CHANGELOG.md, app/views/layout.nunjucks, package.json, yarn.lock
=> add meta description tag for improved search engine description

rancher-config/rancher-compose.yml
In conjunction with Prometheus changes, this will reduce the number of logs/events from health checks.
=> Add check parameter

app/views/includes/google-search.nunjucks
=> change location to search_term_string

CHANGELOG.md, app/lib/getSearchType.js, app/lib/isPostcode.js, app/lib/mapLink.js, app/middleware/setSearchType.js, test/integration/resultsPagePlace.js, test/unit/lib/getSearchType.js, test/unit/lib/mapLink.js
=> :earth_africa: prevent start address from appearing for place searches

CHANGELOG.md, app/public/js/openToggle.js, scss-c2s/c2s-results.scss
The opening times menu toggle wasn't working as intended in Internet Explorer. Fixes added to cover older browsers.
Bug fix
=> :rose: IE toggle bug fix

CHANGELOG.md, app/views/includes/openingTimes.nunjucks, app/views/includes/result-item.nunjucks, package.json
Add hidden text so that the links make sense in and out of context. 
WCAG standard 2.4.4 (level A) - link purpose (in context): https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-refs.html
WCAG standard 2.4.9 (level AAA) - link purpose (link only): https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-link.html
=> :see_no_evil: Hidden assistive text

CHANGELOG.md, app/views/results.nunjucks, scss-c2s/c2s-results.scss
Add an on & off toggle to filter the results by open & closed pharmacies.
Reduce the number of people not finding open pharmacy information on evenings and weekends
=> :question: Add open and closed results toggle

CHANGELOG.md, package.json, scss-c2s/c2s-results.scss
Tweaking the responsive design for the on/off toggle and changes to spacing following feedback from the designer.
=> :no_mobile_phones: Responsive design and spacing fixes

CHANGELOG.md, app/public/js/openToggle.js, app/views/includes/openingTimes.nunjucks, app/views/includes/result-item.nunjucks, app/views/layout.nunjucks, app/views/results.nunjucks, scss-c2s/c2s-ie.scss, scss-c2s/c2s-results.scss, scss-c2s/c2s.scss, test/integration/resultsPageGeneral.js
Improvements to general accessibility and usability of the application. 
- Add skip to content links and accessbility help links.
- Changing the on/off toggle to a plain text link to make it clearer on what is being shown and what is the link does.
- Hidden span labels for the result items distance away from location. 
- Changes to the opening times toggle to work on earlier versions of IE and improve accessibility.
- Display navigation menu items on focus aswell as hover.
https://jira.service.nhs.uk/browse/PC-45
=> Accessibility improvements

CHANGELOG.md, app/views/find-help.nunjucks, scss-c2s/c2s.scss, test/integration/searchPage.js
Provide a link to internet services & appliance contractors.
https://jira.service.nhs.uk/browse/PC-39
=> :mega: links to internet services and appliance contractors

.travis.yml, CHANGELOG.md, app/lib/addAddressLine.js, app/lib/mapLink.js, app/middleware/prerender.js, app/views/includes/result-item.nunjucks, config/contentSecurityPolicy.js, config/express.js, config/helmet.js, package.json, test/.eslintrc.json, test/integration/securityHeaders.js, test/unit/lib/addAddressLine.js, test/unit/lib/mapLink.js
Use first non-empty address line in screen reader only text for Map and Direction and Services Available links
=> Use first non-empty address line in service/map screen reader link

CHANGELOG.md, app/views/includes/footer.nunjucks, app/views/includes/header.nunjucks, package.json, yarn.lock
=> Update links in footer and header

CHANGELOG.md, package.json
=> :arrow_up: Bump version number

.nyc.yml, .nycrc.json, CHANGELOG.md, docker-compose-tests.yml, package.json
=> :eyes: Ensure code coverage config is read

CHANGELOG.md, package.json
Also, bump version minor number
=> :notes: Add missing changelog error

CHANGELOG.md, app/views/includes/header.nunjucks, package.json
Default header search action in the front end library is relative so doesn't work on beta.nhs.uk
the default input name also doesn't work. Updated searchAction and searchInputName for header component so search goes to nhs.uk
=> Update header search to use nhs.uk

CHANGELOG.md, app/views/includes/footer.nunjucks, package.json, test/integration/searchPage.js
Change footer cookie policy link to be relative to domain.
Add integration test to prevent this being an issue in the future
=> Make cookie policy link relative

CHANGELOG.md, app/lib/digitalData.js, app/views/error-404.nunjucks, app/views/error.nunjucks, app/views/find-help.nunjucks, app/views/includes/breadcrumbs.nunjucks, app/views/layout.nunjucks, app/views/no-english-location.nunjucks, app/views/places.nunjucks, app/views/results.nunjucks, test/unit/lib/digitalData.js
Updated CHANGELOG as code was released without it being updated at some point
Removed self linking breadcrumb on homepage
Updated digitalData from beta to web tag
This maintains standards of CHANGELOG
Brings breadcrumbs inline with service manual guidance
Allowed consistent analytics
=> Post beta to live tweaks
