nhsuk/connecting-to-services

- .gitmodules
- README.md
- package.json
- server.js
Azure deployments are breaking because it doesn't have access to the GitLab repo. There are 2 steps involved in fixing it:
* Add the deployment key to the GitLab repo
* Update the submodule so it is requested over SSH rather than https (which means the deployment key will work, as opposed to having to send `username:password`)
I originally thought (see below) the vars in the env would be overridden by the `.env` file vars but this is not the case
> We will never modify any environment variables that have already been set
https://www.npmjs.com/package/dotenv#what-happens-to-environment-variables-that-were-already-set
However, this has got me thinking about the whether handling the env vars via submodules is a good idea. This is the second thing that has had to be dealt with differently due …
> :pill: Fix Azure repo cloning

- .bithoundrc
- .eslintignore
- app/views/includes/foot.nunjucks
- app/views/layout.nunjucks
- assets/javascripts/modules/cookie-message.js
- assets/javascripts/nhsuk.js
- package.json
- public/js/nhsuk.bundle.js
- webpack.config.js
This change adds the functionality to have the cookie message be dynamic and inline with how it works on the beta site.
Additional work required:
* Have `nhsuk.bundle.js` not be committed to source control and have it generated as part of the deployment
* Add ability to have the file minimised for deployments in non-dev environments
This has been facilitated by https://www.npmjs.com/package/webpack which seems to be the 'better/more popular' version of things like https://www.npmjs.com/package/browserify and https://www.npmjs.com/package/requirejs
Fixes #50
> :accept: Make cookie message dynamic

- .travis.yml
- package.json
I've also made the githooks do the same as CI in so far as generating coverage which in turn runs the tests and checking the coverage.
Hopefully this will also help to prevent some of the build failures we have seen. Should also speedup the builds.
> :birthday: Don't run tests twice on CI

- app/middleware/services.js
- app/views/call-111.nunjucks
- app/views/find-help.nunjucks
- app/views/includes/foot.nunjucks
- app/views/index.nunjucks
- app/views/results.nunjucks
- app/views/stomach-ache.nunjucks
- config/routes.js
- test/integration/app.js
Setup the app to minimise the amount of route rewriting required. Just at the moment this means the 'home' page is `/symptoms/stomach-ache` rather than `/`. I've specifically not made the routes take the symptom as a variable as that can be done as the next symptom is added. And symptom is likely going to need to be variable as it could also be condition.
Fixes #69
> :rocket: Route for no rewriting

- package.json
BitHound failed to ignore vendor files as it was silently borking
with a non valid json .bithoundrc file. Add this to prevent this
happening again.
The convoluted cat command is due to this: https://github.com/eslint/eslint/issues/4829
> :facepunch: Prevent future silent BitHound failure

- app/lib/getPharmacies.js
- app/lib/openingTimesParser.js
- app/middleware/getPharmacies.js
- app/views/results-file.nunjucks
- package.json
- test/integration/app.js
- test/unit/lib/getPharmacies.js
- test/unit/lib/openingTimesParser.js
Using the latest branch from `moment-opening-times` e.g. git://github.com/nhsuk/moment-opening-times.git#feature/change-opening-times-format added the functionality to show open results on the results-file route.
I've made some changes to the openingTimes parser to ensure all existing functionality on the main results route continues to work.
The addition of checking the orgs for whether they are open or not has increased the duration of the filter operation. I'll look at reducing that next...
> :high_brightness: Added only open results

- app/lib/getPharmacies.js
- package.json
- test/unit/lib/getPharmacies.js
3 orgs are returned in the middle of the night e.g. 2-4 am from this point. The other point was too far away from a good selection of orgs with wide ranging opening times.
And, I noticed 2 instances of moment were being used to check for the opening times. This could have caused it to have been open for the check in one instant and then shut in the other. Now the same value is used for both checks.
I've also included the change to use the latest version of the moment lib repo since the changes are all merged into master and are working.
> :metal: Search from point with greater choice

- app/lib/mapLink.js
- app/middleware/prerender.js
- app/views/results.nunjucks
- package.json
- test/unit/lib/mapLink.js
No error handling added atm, which is as it was previously. It will still blow up should there not be any address on the item. However, what to do in this scenario needs a bit of thinking about so whilst that is going on this should add some value without degrading what was previously there.
I've added a package for providing the functionality for `Object.values(obj)` which is pretty handy for getting the values of the `obj`. This is functionality that is added in node 8+ but not available in 6 
Fixes #116
> :pushpin: Provide as much context in maps link as possible

- app/views/includes/analytics.nunjucks
- app/views/includes/foot.nunjucks
- app/views/layout.nunjucks
Fixes #138 
If there was a page not found on a route 2 levels above where the pages are normally served from assets were missing e.g. `/finders/find-help/unknown`
> :bug: Fix asset path routing in views

- web.config
Setting up environment in Azure to test the change before merging where it will be automatically deployed to the staging slot.
New slot added and pointing to this branch i.e. `feature/https-all-traffic`
http://connecting-to-services-steve-test.azurewebsites.net/
The site automatically redirects to https://connecting-to-services-steve-test.azurewebsites.net/finders/find-help
Fixes #146
> :closed_lock_with_key: Set Azure to redirect all traffic to https

- app/views/layout.nunjucks
- app/views/results.nunjucks
For webtrends - In order to know what type of services are displayed in the results a meta tag needs to be added to the page. When the service types are more than just pharmacies this will need to be dynamically generated rather than hard coded as it is now.
The information would most likely come from the `organisationType` property on the org data. When there are more than one service type in the results these should be semicolon (`;`) separated.
> :blue_heart: Add meta tag for service type tracking on results

- app/lib/getPharmacies.js
- test/unit/lib/getPharmacies.js
This fixes a bug that was introduced when [open objects started to be cloned](https://github.com/nhsuk/connecting-to-services/commit/a0575433f36e783f476e32e168602825385f8980). The problem being that both `isOpen` and `openingTimesMessage` were not added to the object being cloned before it was cloned. This can be seen on the website by simply visiting the results page for the first time with a new postcode. No opening time message will be displayed. This changes fixes that so the message should be displayed immediately and consistently (as it has been in the past).
> :relieved: Clone open obj once opening info has been added

- web.config
The change here should mean that when the code is deployed by Azure the headers of `Server` and `X-Powered-By` are no longer returned to the client. This can only be tested on Azure.
I've setup https://connecting-to-services-steve-test.azurewebsites.net/finders/find-help to pull from this branch so it can be tested.
Note that neither of the 2 aforementioned headers are present on this site whereas they are on https://connecting-to-services-staging.azurewebsites.net/finders/find-help
This change doesn't alter the scan grade from [https://securityheaders.io](https://securityheaders.io/?q=https%3A%2F%2Fconnecting-to-services-steve-test.azurewebsites.net%2Ffinders%2Ffind-help&hide=on&followRedirects=on) but removing as much info from possible is good practice.
As can be seen here:
Excessive …
> :fire_engine: Remove X-Powered-By and Server headers

- .bithoundrc
In `splunk-bunyan-logger` there is a vulnerable dependency. This has been patched by Synk but bitHound doesn't know that.
This change mutes that dependency warning (as it has been dealt with).
> :ferris_wheel: Mute dep that has been patched by synk

- config/express.js
- test/integration/app.js
Changes based on:
`Content-Security-Policy: default-src https://scotthelme.co.uk:*` would only allow assets to be loaded from my domain over https on any port.
Sourced from https://scotthelme.co.uk/content-security-policy-an-introduction/
> :hotsprings: Allow hotjar.com access over any port

- app.json
To test this works the review apps should work right off the bat and any logs should be getting pumped straight into Splunk
> :confounded: Make review apps use splunk logging

- app/middleware/setLocals.js
- app/views/find-help.nunjucks
Use the `referer` header value if present otherwise fall back to JS version. The reason for the fallback is due to the header not guaranteed to be sent.
> :tea: Remove hard coded back link

- package.json
Fixes an issue where network connectivity loss to the
Splunk Http Event Collector would throw an exception
that bubbled up to the consumer of the library and
caused that consumer to crash. Rather than handle the
exception in the consumer the library takes care of it.
In order to test the change has been successful the most robust way I've found is to run the site locally with the network turned off. If the logger changes are good the site will continue to function when it tries to load the `/finders/find-help` page. The site will 'have technical' problems if a search is done due to postcodes.io not being able to be reached. This is as expected.
The Splunk stream is used only in a production environment. In order to run the app so it will attempt to log to Splunk, the command to run is: …
> :do_not_litter: Use logger that doesn't throw exceptions

- config/express.js
- test/integration/app.js
Using `child-src` rather than `frame-src` due to `frame-src` having been [deprecated](https://www.w3.org/TR/CSP2/#directive-frame-src)
To confirm this is working (at least before it is deployed to a site where the survey will be active) navigate to the results page of the deployment and check there are no warnings in the browser's console about `Refused to frame 'https://vars.hotjar.com/rcj-hotjar-265857.js?sv=5:44` (or similar). To see what errors are occurring - check them out on the live or staging site.
> :bug: Whitelist hotjar to get survey to work

- .travis.yml
I don't think there is a reason why the image should be created if the build has failed so I've changed the life cycle event to only do it when previous steps have been successful.
Source: https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
Fixes #246
> :bug: Build Docker image and env on success only

- .travis.yml
Instead of running tests on the CI's host OS we should be running them inside of the container. Using the `git-hook` script, linting is done, tests are run, code coverage generated and uploaded to both coveralls and codacy.
> :package: Run tests in container

- .travis.yml
This PR needs to be merged before #284 Note, it merges into branch `feature/yarnify` as opposed to `master`
> :no_entry: No longer need pyaml for deployments

- .gitignore
- .snyk
- docker-compose-tests.yml
- docker-compose.yml
- package.json
- yarn.lock
This change gets snyk to run during CI. It will update snyk for every build which in turn will fail the build if there are vulnerabilities discovered.
> :boom: Small change to test snyk

- CHANGELOG.md
- config/express.js
- package.json
- test/integration/securityHeaders.js
Reason for being less specific on the domains is due to occassional
changes by the third parties which causes functionality to stop working
on our site.
Removal of scheme specification as it defaults to how the page has been
accessed.
> :raising_hand: Be less specific about third party domains

- CHANGELOG.md
- package.json
The metrics test is no longer run on the git-hook, only during the CI test.
The metrics test needs the site running to return the expected results and only works in the container, not in the git-hook when running locally. The git hook would always fail when running locally.
The test has been disabled locally, but continues to run in the CI tests.
> ignore metrics test

- CHANGELOG.md
- README.md
- doc/adr/0008-add-basic-authentication-to-test-environments.md
- package.json
- rancher-config/docker-compose.yml
Adds basic auth to the service. Controlled via vault variables. By default all environments are protected. Overridden for environments that require access by all.
> :closed_lock_with_key: Add basic authentication to test environments in Rancher

- .snyk
- app/lib/mapLink.js
- app/lib/messages.js
- app/lib/setLocationsOnLocals.js
- app/middleware/locals.js
- app/middleware/locationValidator.js
- app/middleware/performPlaceSearch.js
- app/middleware/prerender.js
- app/middleware/setLocals.js
- app/views/find-help.nunjucks
- app/views/includes/no-place-results.nunjucks
- app/views/includes/place-results.nunjucks
- app/views/places.nunjucks
- app/views/results.nunjucks
- test/integration/locate.js
- test/integration/resultsPagePlace.js
- test/integration/resultsPagePostcode.js
- test/lib/expectations.js
- test/unit/lib/messages.js
- yarn.lock
`Enter a place or a postcode` on initial search screen is now `Enter a town, city or postcode`.
If a term is not found in a search, the search term is now surrounded by single quotes on the error page.
`There are n places matching x` is now `We found n places that match 'y'`.
`Please select your location from the list below to continue.` is now `Choose one of the following:`. The text has moved from the header into a styled `p` tag.
The search term on the results page is the cleansed search term rather than a string built of the address returned from the lookup.
> :bowtie: content change: search message, quotes, disambiguation

- CHANGELOG.md
- app/middleware/routeHelper.js
- test/integration/resultsPagePlace.js
- test/integration/resultsPagePostcode.js
Label was incorrect for no postcode results - it was 'You must enter a town, city or postcode to find a pharmacy.' rather than 'Enter a town, city or postcode in England'.
> :eyes: display correct search field label when no postcode results

- CHANGELOG.md
- rancher-config/docker-compose.yml
This change fixes the problem of the deployed application not having the correct mapping for Google Analytics Id, resulting in no GA script being included in the app and thus no GA tracking.
Previously there were entries for both `GOOGLE_ANALYTICS_TRACKING_ID` and `GOOGLE_ID` in the vault. However, to remove duplication and increase consistency across Tracking Ids all Tracking Ids are now `XXXXXXX_ANALYTICS_TRACKING_ID`.
> :bug: Correct reference for GA Id

- CHANGELOG.md
- app/lib/displayOpenResults.js
- app/lib/resultsPageAltUrl.js
- app/lib/utils.js
- app/middleware/setLocals.js
- app/views/includes/result-item.nunjucks
- app/views/results.nunjucks
- test/integration/resultsPageGeneral.js
- test/unit/lib/displayOpenResults.js
- Extracted `displayOpenResults` so it can be shared
- Reorder the setting of the locals to alphabetical to make it easier to scan through
> :accept: Extract displayOpenResults into shareable module

- CHANGELOG.md
- app/lib/locate.js
- app/lib/promCounters.js
- app/lib/promHistograms.js
- app/middleware/countChecks.js
- config/routes.js
- doc/adr/0009-search-by-place.md
- package.json
- test/integration/metrics.js
Counts are still available. Histograms have the benefit they response
time to the external call can be monitored.
> :put_litter_in_its_place: Replace location lookups with histograms

- app/lib/dateUtils.js
- app/lib/handleReverseGeocodeError.js
- app/lib/mappers/azContactMapper.js
- app/lib/mappers/azMapper.js
- app/lib/mappers/azOpeningTimesMapper.js
- app/lib/postcodes.js
- app/lib/queryBuilder.js
- app/middleware/getPharmacies.js
- app/middleware/performPlaceSearch.js
- test/unit/lib/mappers/azContactsMapper.js
- test/unit/lib/queryBuilder.js
Additional opening times for phamacies (and possibly other org types)
can have a type of _either_ Additional or General.  This is an error in
the source data which seems to have been introduced in 2013 and never
corrected.  We have extended the guard rather than remove it (since
'additionalness' can be infered by a non-zero AdditionalOpeningDate) to
filter out any future opening times for different types (e.g. reception)
> Guard against data inconsistency

- CHANGELOG.md
- app/lib/queryBuilder.js
- test/unit/lib/queryBuilder.js
This is to ensure only community pharmacies appear in results and
appliance/internet/etc do not
> Add subtype to pharmacy filter

- app/lib/queryBuilder.js
- test/unit/lib/queryBuilder.js
The query logic was using the default precedance (which was wrong)
and was return all orgs which were open as a result of additional
hours regardless of org type.
> Query was returning all orgs open on a bank holiday
